```{r}
library(tidyverse)
library(dplyr)
source("helper_functions.R")
```


#Initialize parameters
```{r}
investigate_date <- seq(10,600,10)
sim_days <- 601
n <- 50000

inc.pd <- 5
rec.pd <- 7
num_int <- 25
prop_rec <- 0.02 # need to debug if this is 0
prop_symp <- 1/3
R <- 2
days_reinf <- 30 # number of days before have chance of reinfection
reinf <- 0.5 # relative probability of reinfection
prop_vax <- 0.2
days_wane <- 0 # number of days for immunity starts to wane after gaining immunity
wane_rate <- 0.01
beta <- R/rec.pd
vax_days = seq(1,600,15)

infectious_num <- list()
cumulative_case <- list()
new_case_daily <- list()
cumu_case <- 0
```

#Initialize nodes
the starting day of the entire simulation is day 1 (not day 0)
```{r}
S_nodes <- bind_cols(
  ID = 1:(n - num_int * 2 - prop_rec * n), 
  vax_day = NA, VEs = 0, VEp = 0, prior_inf = 0, 
  day_prior_inf = NA, day_exposed = NA, symp = NA, 
  day_inf = NA, day_rec = NA,
  history = "1",  # event history
  immunity = 0,  # Immunity level
  immunity_start = NA,  # Start date of immunity
  immunity_model = 0, #immunity level at the time of infection or current immunity level
  dpv = NA, #day post vaccination
  status = "susceptible"
)

day_exposed <- sample(-1:1, num_int, replace = TRUE)
E_nodes <- bind_cols(
  ID = (n - num_int * 2 - prop_rec * n + 1):(n - num_int * 2 - prop_rec * n + num_int),
  vax_day = NA, VEs = 0, VEp = 0, prior_inf = 0,
  day_prior_inf = NA, day_exposed = day_exposed, symp = NA, 
  day_inf = day_exposed + inc.pd, day_rec = day_exposed + inc.pd + rec.pd,
  history = "2",  # event history
  immunity = 0.75,  # Immunity level
  immunity_start = day_exposed,  # Start date of immunity
  immunity_model = 0, # immunity level at the time of infection or current immunity level
  dpv = NA, # day post vaccination
  status = "exposed"
)

I_nodes <- bind_cols(
  ID = (n - num_int * 2 - prop_rec * n + num_int + 1):(n - num_int * 2 - prop_rec * n + num_int * 2), 
  vax_day = NA,  VEs = 0, VEp = 0, prior_inf = 0,
  day_prior_inf = NA, day_exposed = 1-inc.pd, symp = rbinom(num_int,1,prop_symp),
  day_inf = 1, day_rec = 1+rec.pd,
  history = "2",  # event history
  immunity_start = 1-inc.pd, # Start date of immunity
  immunity = 0.75, # Immunity level
  immunity_model = 0, #immunity level at the time of infection or current immunity level
  dpv = NA, #day post vaccination
  status = "infectious"
  )

R_nodes <- bind_cols(
  ID = (n - num_int * 2 - prop_rec * n + num_int * 2 + 1):n,
  vax_day = NA,  VEs = 0, VEp = 0, prior_inf = 1,
  day_prior_inf = sample(seq(-100,-(inc.pd+rec.pd),1),prop_rec*n,replace=TRUE)) %>%
    mutate(
  day_exposed = day_prior_inf, symp = NA, day_inf = day_prior_inf+inc.pd, 
  day_rec = day_prior_inf+inc.pd+rec.pd,
  history = "23",  # event history
  immunity_model = 0, #immunity level at the time of infection or current immunity level
  immunity_start = day_prior_inf, # Start date of immunity
  immunity = pmax(0.75-(1-immunity_start)* wane_rate, 0),# Immunity level 
  dpv = NA, #day post vaccination
  status = "recovered"
  ) 
```


#Simulation loop
```{r}
for (t in 1:sim_days) {
  cat(t) #report simulation date in console
  
  epidemic_curve <- NULL
  case_daily <- 0
  
  
  # vaccinate if current day is one of the "vax days"
  if (t %in% vax_days){
    S_nodes <- vaccinate(S_nodes,t)
    R_nodes <- vaccinate(R_nodes,t)
    E_nodes <- vaccinate(E_nodes,t)
    I_nodes_symp_0 <- I_nodes[I_nodes$symp == 0, ]
    I_nodes_symp_1 <- I_nodes[I_nodes$symp == 1, ]
    I_nodes_symp_0 <- vaccinate(I_nodes_symp_0, t)
    I_nodes <- rbind(I_nodes_symp_0, I_nodes_symp_1)
    }
        

  # Update immunity level with waning
  # Only the immunity of susceptible and recovered agents can wane. The immunity level of exposed and infectious agents remain unchanged
  S_nodes <- wane(S_nodes, t)
  R_nodes <- wane(R_nodes, t)
  
  # I -> R 
  recover_I <- recover(I_nodes, t)
  I_nodes <- recover_I[[1]]
  R_nodes <- bind_rows(R_nodes, recover_I[[2]])
  
  # E -> I
  new_infectious <- E_to_I(E_nodes, t)
  E_nodes <- new_infectious[[1]]
  I_nodes <- bind_rows(I_nodes, new_infectious[[2]])
  
# Infect S
if (nrow(S_nodes) > 0) {
  S_nodes2 <- S_nodes
  for (node in 1:nrow(S_nodes)) {
    inf <- rbinom(1, 1, beta * (1 - (S_nodes$immunity_model[node])^3) * (nrow(I_nodes)/n))
    if (inf == 1) {
      S_nodes2 <- subset(S_nodes2, ID != S_nodes$ID[node])
      new_exposed_susceptible <- S_nodes %>%
        subset(ID == S_nodes$ID[node]) %>%
        mutate(day_exposed = t,
               immunity_start = t,
               day_inf = t + inc.pd,
               day_rec = t + inc.pd + rec.pd,
               history = paste0(history, "2"),
               status = "exposed") %>% 
        mutate(immunity = case_when(grepl("2", history) & grepl("4", history) ~ 1, #infected given vaccinated
                                    grepl("2", history) & !grepl("4", history) ~ 0.75,
                                    TRUE ~ immunity))
      case_daily <- case_daily + nrow(new_exposed_susceptible)
      E_nodes <- bind_rows(new_exposed_susceptible, E_nodes)
    }
  }
  S_nodes <- S_nodes2
}

# Infect R
if (nrow(R_nodes) > 0) {
  R_nodes2 <- R_nodes
  for (node in 1:nrow(R_nodes)) {
    inf <- rbinom(1, 1, beta * (1 - (R_nodes$immunity_model[node])^3) * (nrow(I_nodes)/n))
    if (inf == 1) {
      R_nodes2 <- subset(R_nodes2, ID != R_nodes$ID[node])
      new_exposed_recover <- R_nodes %>%
        subset(ID == R_nodes$ID[node]) %>%
         mutate(day_exposed = t,
               immunity_start = t,
               day_inf = t + inc.pd,
               day_rec = t + inc.pd + rec.pd,
               history = paste0(history, "2"),
               status = "exposed",
               immunity = 1)
      case_daily <- case_daily + nrow(new_exposed_recover)
      E_nodes <- bind_rows(new_exposed_recover, E_nodes)
    }
  }
  R_nodes <- R_nodes2
}
  
  cumu_case <- cumu_case + case_daily
  cumulative_case <- append(cumulative_case, list(cumu_case))
  new_case_daily <- append(new_case_daily, list(case_daily))
  R_nodes <- R_nodes2
  
  epidemic_curve <- bind_rows(epidemic_curve, E_nodes, I_nodes)
  print(nrow(I_nodes))
  
  if (!is.null(epidemic_curve)) {
    if (t %in% investigate_date) {
    specific_day_results <- epidemic_curve %>%
      mutate(eventstatus = 1) %>%
      bind_rows(S_nodes %>%
                  mutate(eventstatus = 0)) %>%
      bind_rows(R_nodes %>%
                  mutate(eventstatus = 0)) %>%
      mutate(TrialStatus = ifelse(is.na(vax_day), 0, 1),
             RI = ifelse(prior_inf == 1 & eventstatus == 1, 1, 0)) %>%
      rename(PI = prior_inf, Symptomatic = symp) %>%
      dpv(t) %>%
      mutate(prop_rec = prop_rec, 
             prop_symp = prop_symp,
             R = R,
             days_reinf = days_reinf,
             reinf = reinf,
             sim_days = sim_days,
             VEs = VEs,
             VEp = VEp,
             prop_vax = prop_vax,
             days_wane = days_wane,
             wane_rate = wane_rate,
             day = t)
    infectious_num <- append(infectious_num, list(nrow(I_nodes) + nrow(E_nodes)))
      write.csv(specific_day_results, paste0(n, "_simulation_1028_cubic_", t, ".csv"))
    }
  }
}
```


```{r}

```

